---
title: Trey’s Thoughts
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: trey@treypiepmeier.com
description: 'This is Trey Piepmeier''s blog. He writes about photography and web
  development and music and being outside.

'
baseurl: ''
url: https://words.treypiepmeier.com
twitter_username: trey
github_username: trey
markdown: kramdown
permalink: "/:year/:month/:title"
